/* global React */
function Policy({ kind, navigate }) {
  const isPrivacy = kind === 'privacy';
  return (
    <div className="container">
      <div className="policy">
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: 'var(--ink-3)', marginBottom: 20, fontFamily: 'var(--font-mono)' }}>
          <a href="#" onClick={(e) => { e.preventDefault(); navigate('home'); }} style={{ color: 'var(--primary)' }}>← Home</a>
          <span>/</span>
          <span>{isPrivacy ? 'privacy-policy' : 'terms-of-use'}</span>
        </div>
        <h1>{isPrivacy ? 'Privacy Policy' : 'Terms of Use'}</h1>
        <div className="updated">Last updated: May 14, 2026</div>

        {isPrivacy ? (
          <>
            <p>
              Campaign Creators ("we," "our," or "us") respects your privacy. This Privacy Policy explains how we collect,
              use, and share information when you use the AEO Auditor service (the "Service").
            </p>

            <h2>1. Information we collect</h2>
            <p>When you submit a domain for analysis we collect:</p>
            <ul>
              <li>The domain name you submit and publicly accessible pages from that domain.</li>
              <li>An email address, if you choose to receive your report by email.</li>
              <li>Standard request data — IP address, user agent, and timestamp — used for rate limiting and abuse prevention.</li>
              <li>Cookies and similar technologies to remember your session and improve the Service.</li>
            </ul>

            <h2>2. How we use information</h2>
            <p>We use collected information to:</p>
            <ul>
              <li>Generate and deliver your AEO audit report.</li>
              <li>Improve the Service, including the underlying scoring models.</li>
              <li>Send you the report and, with your permission, occasional product updates.</li>
              <li>Detect and prevent abuse of the Service.</li>
            </ul>

            <h2>3. Sharing</h2>
            <p>
              We do not sell your data. We share information only with vendors that help us run the Service
              (cloud hosting, email delivery, analytics) and only to the extent necessary. We may disclose
              information if required by law.
            </p>

            <h2>4. AI engines & third parties</h2>
            <p>
              To produce your report, we send prompts to third-party AI engines (including ChatGPT, Perplexity,
              Google AI Overviews, and Claude). These prompts do not contain your email or personal information —
              only the domain and topical questions about its industry.
            </p>

            <h2>5. Data retention</h2>
            <p>
              We keep audit reports for 90 days so you can re-access them via the link sent to you. After 90 days,
              identifying information is purged and only aggregated, anonymized data is retained for model improvement.
            </p>

            <h2>6. Your rights</h2>
            <p>
              You may request access, correction, or deletion of your data at any time by emailing
              <span className="mono"> privacy@campaigncreators.com</span>. We respond to verified requests within 30 days.
            </p>

            <h2>7. Contact</h2>
            <p>
              Questions? Email <span className="mono">privacy@campaigncreators.com</span>.
            </p>
          </>
        ) : (
          <>
            <p>
              These Terms of Use ("Terms") govern your access to and use of the AEO Auditor service (the "Service")
              provided by Campaign Creators. By using the Service, you agree to these Terms.
            </p>

            <h2>1. Eligibility & scope</h2>
            <p>
              The Service is intended for businesses to audit websites they own or have authorization to analyze.
              You may not submit domains you do not have the right to audit.
            </p>

            <h2>2. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service to violate any law or third-party right.</li>
              <li>Submit domains in a manner intended to abuse, overload, or disrupt the Service.</li>
              <li>Attempt to reverse engineer, scrape, or resell any portion of the Service or its output without written permission.</li>
              <li>Misrepresent the source or accuracy of reports generated by the Service.</li>
            </ul>

            <h2>3. Audit reports</h2>
            <p>
              Reports are generated algorithmically and reflect a point-in-time analysis. They are provided "as is" for
              informational purposes. Recommendations are not guarantees of search ranking or business outcomes.
            </p>

            <h2>4. Intellectual property</h2>
            <p>
              The Service, including its scoring methodology, copywriting, visual design, and software, is owned by
              Campaign Creators. You receive a limited, non-exclusive license to view and share the report we generate for you.
            </p>

            <h2>5. Disclaimer of warranties</h2>
            <p>
              The Service is provided on an "as is" and "as available" basis. To the maximum extent permitted by law,
              Campaign Creators disclaims all warranties, express or implied, including merchantability, fitness for a
              particular purpose, and non-infringement.
            </p>

            <h2>6. Limitation of liability</h2>
            <p>
              In no event shall Campaign Creators be liable for any indirect, incidental, special, consequential, or
              punitive damages arising from your use of, or inability to use, the Service.
            </p>

            <h2>7. Changes</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes are posted
              constitutes acceptance of the updated Terms.
            </p>

            <h2>8. Contact</h2>
            <p>
              Questions about these Terms? Email <span className="mono">legal@campaigncreators.com</span>.
            </p>
          </>
        )}
      </div>
    </div>
  );
}

window.Policy = Policy;
